### ISSUE TITLE
SetDefault is not defined

### ISSUE THREAD

**Issue by marcorocci** [acropia/PHP-WinRM#3]
Hi,
on protocol.php
https://github.com/acropia/PHP-WinRM/blob/master/winrm/protocol.php

seDefault is not defined on php array.
Any suggestions?

**Comment by igoralentyev** [comment]
@marcorocci Hi! Did you find a solution for this issue? Same problem

**Comment by marcorocci** [comment]
Of course, if you want to use a winrm ready to use, you can use this python lib https://github.com/diyan/pywinrm
and you can use it from php system call, you can see this project: https://github.com/diyan/pywinrm

**Comment by igoralentyev** [comment]
@marcorocci Thanks a lot! But it seems like your last link is incorrect? :)

**Comment by marcorocci** [comment]
@igoralentyev yes sorry, this is the project: https://github.com/kroshilin/winrm

**Comment by igoralentyev** [comment]
@marcorocci thanks a lot!
